In [2]:
import os
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

path_classes = Path("/data_lids/home/taylla/PycharmProjects/meso/data"
                    "/classes_subclasses_nodular.csv")
path_images = Path("/data_lids/home/taylla/PycharmProjects/meso/data/resample"
                   "/images_orig_reg")
path_masks_dilated = Path("/data_lids/home/taylla/PycharmProjects/meso/output/"
                          "/HyperparameterTuning/Dilation")
path_metrics_train = Path("/data_lids/home/taylla/PycharmProjects/meso"
                          "/output/HyperparameterTuning/exp_dilatation_P"
                          "/dilated_patient/SLIC/split_class/train"
                          "/metrics_dilated_patient_slic_train.csv")
path_metrics_test = Path("/data_lids/home/taylla/PycharmProjects/meso/output"
                         "/HyperparameterTuning/exp_dilatation_P"
                         "/dilated_patient/SLIC/split_class/test"
                         "/metrics_dilated_patient_slic_test.csv")
path_metrics_out = Path("/data_lids/home/taylla/PycharmProjects/meso"
                            "/output/quantitative_analysis/classification/slic")
os.makedirs(path_metrics_out, exist_ok=True)
path_splits = Path("/data_lids/home/taylla/PycharmProjects/meso/data/splits")


df_slic_train = pd.read_csv(path_metrics_train, index_col=0)
df_slic_train.head()

# df_slic_test = pd.read_csv(path_metrics_test)
# #get the columns names
columns = df_slic_train.columns
#
# #get the rows names
rows = df_slic_train.index
#
print(rows)
print(columns)
# # # drop rows with all TP = 0 and TN = 0

transposed_data = df_slic_train.transpose()
# transposed_data.columns = transposed_data.iloc[
#     0]  # Set the first row as header

# Convert TP and TN to numeric type to filter properly
transposed_data['TP'] = pd.to_numeric(transposed_data['TP'])
transposed_data['TN'] = pd.to_numeric(transposed_data['TN'])

# Filter out rows where TP or TN are zero
filtered_data = transposed_data[
    (transposed_data['TP'] != 0) & (transposed_data['TN'] != 0)]
# save the filtered data
data = filtered_data.copy()

data.drop(columns=['FP_ID', 'FN_ID'], inplace=True)
print(data)

Index(['acc', 'balanced_acc', 'average_precision_score', 'f1_score', 'AUC',
       'Sensitivity', 'Specificity', 'PPV', 'NPV', 'FP', 'FN', 'TN', 'TP',
       'FP_ID', 'FN_ID', 'CCR'],
      dtype='object')
Index(['0.1_0.0001', '0.1_0.0003', '0.1_0.0005', '0.1_0.0007', '0.1_0.001',
       '0.1_0.003', '0.1_0.005', '0.1_0.007', '0.1_0.01', '0.1_0.03',
       '0.1_0.05', '0.1_0.07', '0.1_0.1', '0.1_50', '0.1_100', '0.1_150',
       '0.1_200', '0.1_250', '0.1_300', '0.1_350', '0.1_400', '0.1_450',
       '0.1_500', '0.1_550', '0.1_600', '0.1_650', '0.1_700', '0.1_750',
       '1_0.0001', '1_0.0003', '1_0.0005', '1_0.0007', '1_0.001', '1_0.003',
       '1_0.005', '1_0.007', '1_0.01', '1_0.03', '1_0.05', '1_0.07', '1_0.1',
       '1_50', '1_100', '1_150', '1_200', '1_250', '1_300', '1_350', '1_400',
       '1_450', '1_500', '1_550', '1_600', '1_650', '1_700', '1_750',
       '10_0.0001', '10_0.0003', '10_0.0005', '10_0.0007', '10_0.001',
       '10_0.003', '10_0.005', '10_0.007', '10_0.01', '10_0.03', '10_0.05',
       '10_0.07', '10_0.1', '10_50', '10_100', '10_150', '10_200', '10_250',
       '10_300', '10_350', '10_400', '10_450', '10_500', '10_550', '10_600',
       '10_650', '10_700', '10_750'],
      dtype='object')
                            acc         balanced_acc average_precision_score  \
0.1_0.0001   0.3939393939393939  0.45238095238095233      0.6171236171236171
0.1_0.0003   0.5454545454545454   0.5714285714285714      0.6734693877551021
0.1_0.0005   0.5757575757575758   0.5773809523809523       0.676088617265088
0.1_0.0007   0.5454545454545454   0.5178571428571429      0.6448051948051948
0.1_0.001    0.5757575757575758   0.5416666666666666      0.6565656565656566
...                         ...                  ...                     ...
10_550      0.48484848484848486  0.41666666666666663       0.601010101010101
10_600       0.5454545454545454  0.44642857142857145      0.6127087198515769
10_650       0.5454545454545454  0.44642857142857145      0.6127087198515769
10_700       0.5151515151515151   0.4226190476190476      0.6030142696809364
10_750       0.6060606060606061  0.49404761904761907      0.6336219336219335

                      f1_score                  AUC          Sensitivity  \
0.1_0.0001  0.3333333333333333  0.45238095238095244  0.23809523809523808
0.1_0.0003  0.5714285714285714   0.5714285714285715  0.47619047619047616
0.1_0.0005   0.631578947368421   0.5773809523809523   0.5714285714285714
0.1_0.0007  0.6341463414634146   0.5178571428571428   0.6190476190476191
0.1_0.001   0.6666666666666666   0.5416666666666666   0.6666666666666666
...                        ...                  ...                  ...
10_550      0.6222222222222222  0.41666666666666663   0.6666666666666666
10_600      0.6938775510204082   0.4464285714285715   0.8095238095238095
10_650      0.6938775510204082   0.4464285714285715   0.8095238095238095
10_700      0.6666666666666666   0.4226190476190476   0.7619047619047619
10_750      0.7450980392156863  0.49404761904761907   0.9047619047619048

                   Specificity                 PPV                  NPV  FP  \
0.1_0.0001  0.5555555555555556  0.5555555555555556   0.3333333333333333   4
0.1_0.0003  0.7142857142857143  0.7142857142857143  0.42105263157894735   4
0.1_0.0005  0.7058823529411765  0.7058823529411765               0.4375   5
0.1_0.0007                0.65                0.65  0.38461538461538464   7
0.1_0.001   0.6666666666666666  0.6666666666666666   0.4166666666666667   7
...                        ...                 ...                  ...  ..
10_550      0.5833333333333334  0.5833333333333334   0.2222222222222222  10
10_600      0.6071428571428571  0.6071428571428571                  0.2  11
10_650      0.6071428571428571  0.6071428571428571                  0.2  11
10_700      0.5925925925925926  0.5925925925925926  0.16666666666666666  11
10_750      0.6333333333333333  0.6333333333333333   0.3333333333333333  11

            FN  TN  TP                 CCR
0.1_0.0001  16   8   5  0.4482758620689655
0.1_0.0003  11   8  10  0.6206896551724138
0.1_0.0005   9   7  12  0.6785714285714286
0.1_0.0007   8   5  13  0.6923076923076923
0.1_0.001    7   5  14  0.7307692307692307
...         ..  ..  ..                 ...
10_550       7   2  14  0.6956521739130435
10_600       4   1  17  0.8181818181818182
10_650       4   1  17  0.8181818181818182
10_700       5   1  16  0.7727272727272727
10_750       2   1  19  0.9090909090909091

[72 rows x 14 columns]

In [19]:
# separate each collum into a new dataframe
# TP
acc = data.acc.to_frame()
b_acc = data.balanced_acc.to_frame()
avg_prec = data.average_precision_score.to_frame()
f1 = data.f1_score.to_frame()
sens = data.Sensitivity.to_frame()
spec = data.Specificity.to_frame()
ppv = data.PPV.to_frame()
npv = data.NPV.to_frame()
auc = data.AUC.to_frame()
tn = data.TN.to_frame()
tp = data.TP.to_frame()
fn = data.FN.to_frame()
fp = data.FP.to_frame()

In [24]:
# analyse how auc varies
# auc = data.AUC.to_frame()
auc = auc.sort_values(by='AUC', ascending=False)

In [25]:
auc

                            AUC
0.1_0.0005   0.5773809523809523
0.1_0.0003   0.5714285714285715
1_200        0.5654761904761905
10_200       0.5654761904761905
10_0.001     0.5595238095238095
...                         ...
1_500        0.4226190476190476
10_550      0.41666666666666663
1_550       0.41666666666666663
1_450       0.39880952380952384
10_450      0.39880952380952384

[72 rows x 1 columns]

In [27]:
# analyse the variation on auc the mean and std
auc['AUC'] = auc['AUC'].astype(float)

In [28]:
auc.describe()

             AUC
count  72.000000
mean    0.490493
std     0.045515
min     0.398810
25%     0.462798
50%     0.485119
75%     0.523810
max     0.577381

In [30]:
# selec all rows with auc > 0.5
auc_50 = auc[auc['AUC'] > 0.5]
auc_50

                 AUC
0.1_0.0005  0.577381
0.1_0.0003  0.571429
1_200       0.565476
10_200      0.565476
10_0.001    0.559524
1_0.001     0.559524
10_0.0007   0.559524
1_0.0007    0.559524
10_0.01     0.559524
1_0.01      0.559524
0.1_0.007   0.559524
0.1_50      0.553571
0.1_0.001   0.541667
10_0.0001   0.535714
1_0.0001    0.535714
10_0.0003   0.523810
1_300       0.523810
1_0.0003    0.523810
10_300      0.523810
0.1_0.005   0.517857
0.1_0.01    0.517857
0.1_0.0007  0.517857
0.1_750     0.517857
0.1_0.003   0.511905
1_0.003     0.505952
0.1_200     0.505952
10_0.003    0.505952